import Head from "next/head";
import { PROJECT_NAME } from "../src/constants/projectGenerics";
import Banner from "../src/components/banner"
import Plans from "../src/components/plans";
import ContactUs from "../src/components/contactUs";
import AboutUs from "../src/components/aboutUs";
import { HomeContainer } from "./styles";

const Home = (props) => {
  return (
    <>
      <Head>
        <title>{PROJECT_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoDos.png" />
      </Head>

      <HomeContainer>
        <Banner />
        <Plans />
        <AboutUs />
        <ContactUs />
      </HomeContainer>
    </>
  );
}

export default Home